[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm prisma:generate && pnpm build"

[deploy]
startCommand = "pnpm start:prod"
healthcheckPath = "/api"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
